### ISSUE TITLE
Fix KeyError on Cropped_image step with a specific image

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN_Snakemake#11] opened 2022-03-31 15:14 UTC
I am receiving an error when running the cropping step  cropping the `UWZM-F-0001699.jpg` using `crop_image.py` in `library://thibaulttabarin/bgnn/crop_image:v1`. Please update the associated code to fix the error if possible. If the error is unavoidable please print out a more meaningful error message. 

### Error Details
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 630, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'F'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pipeline/scripts/crop_image.py", line 52, in <module>
    main(sys.argv[1],sys.argv[2],sys.argv[3])
  File "/pipeline/scripts/crop_image.py", line 48, in main
    im1.save(output_file)
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 632, in _save
    raise OSError(f"cannot write mode {im.mode} as JPEG") from e
OSError: cannot write mode F as JPEG
```

### Reproducing
The problem can be reproduced with just singularity in a directory with UWZM-F-0001699.jpg and UWZM-F-0001699.json:
```
singularity exec library://thibaulttabarin/bgnn/crop_image:v1 /pipeline/scripts/crop_image.py UWZM-F-0001699.jpg UWZM-F-0001699.json outfile.jpg
```

**Comment by johnbradley** [comment] 2022-03-31 15:15
I am unable to locate the source code used to build the `library://thibaulttabarin/bgnn/crop_image:v1` image.
The crop_image.py script can be found at`/pipeline/scripts/crop_image.py` within that container.

**Comment by johnbradley** [comment] 2022-03-31 15:19
The file in question is part of this csv file: https://github.com/hdr-bgnn/BGNN_Snakemake/blob/main/List/list_lepomis.csv

**Comment by thibaulttabarin** [comment] 2022-04-04 15:53
the container is here, https://cloud.sylabs.io/library/thibaulttabarin/bgnn/crop_image
the source code to create the container is still in local. I don't know where to put it. It is a small piece of code, I think i will put in the BGNN_snakemake.
Let me look at it in detail but I think the problem is the following : the gen_metadata rule doesn't work with all the fish, therefore sometime no fish is deteted and then no cropping is possible, I need to put error / execption in the code.

**Comment by hlapp** [comment] 2022-04-04 16:54
@thibaulttabarin if the `crop_image` code is specific to this pipeline then I agree, the best place to put it would be into this repository. But if it's more general than that, it would probably be better to put it into its own repo.

There is no requirement whatsoever, whether formal or from conventions, that a codebase have a certain size to warrant being in its own repo.

That being said, it's easy enough to both separate and merge code to and from, respectively, different repositories later, including while fully maintaining the entire commit history for the code being separated out or merged in. For the former, this is made easiest if the code that one might want to separate out later is in its own subdirectory.

**Comment by johnbradley** [comment] 2022-04-06 13:45
The code in crop.py (at least in the container I pulled) looks generic with the exception of the following function:
```
def get_bbox(metadata_file):

    f = open(metadata_file)
    data = json.load(f)
    first_value = list(data.values())[0]

    if first_value['has_fish']==True:

        bbox = first_value['fish'][0]['bbox']
    else: bbox =[]
    return bbox
```
This code extracts a bounding box from a JSON file created `drexel_metadata` step.

**Comment by thibaulttabarin** [comment] 2022-06-20 21:03
The code now lives in Scripts in this repo. For the moment, all the small tools I am developing specifically for this workflow, Crop_image, Morphology are in [Scripts](https://github.com/hdr-bgnn/BGNN_Snakemake/tree/main/Scripts). Since those functions use a very similar library dependencies, I created a workflow (in Git action) that creates a container with the 2 functions (fairly small), Crop_image_main.py and Morphology_main.py.

**Closed as completed by thibaulttabarin** 2022-06-20 21:03 UTC
